id: AC714167C
title: A Prayer of Devotion, to Make the Tears Fall
type: translation
pechas:
- IDE4E6128
- I03371407
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:38.783154
  last_modified_at: 2023-01-04 12:41:38.783173
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IDE4E6128/3AA1: 9C31
  I03371407/6C4B: 9C31
